<a href="https://colab.research.google.com/github/YusukeAoki57/diveintocode-ml/blob/master/Week2%E6%8E%88%E6%A5%AD%E5%89%8D%E8%AA%B2%E9%A1%8C_%E6%95%B0%E5%AD%A63.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

問題1&問題2 行列積を手計算する/Numpyによる計算

In [ ]:
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

ans=np.matmul(a_ndarray,b_ndarray)
print(ans)


[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


行列の手計算の方法
左の行列の行×右の行列の列を要素ごとに掛け、足し合わせていく

問題3　ある要素の計算を実装

In [ ]:
cal=[]
sum=0
for i in range(len(a_ndarray)):
  for k in range(len(b_ndarray)):
    for z in range(len(b_ndarray)):
      sum=sum+(a_ndarray[k][z]*b_ndarray[z][i])
      #print(sum)
      if z==len(b_ndarray)-1:
        cal.append(sum)
        result=np.array(cal)
        sum=0       
print(result.reshape(3,3).T)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


問題4&5&6　行列積を行う関数の作成/計算が定義されない入力を判定する/転置

In [ ]:
def queue_multi(a,b):
  cal=[]
  sum=0
  for i in range(b.shape[1]):
    for k in range(a.shape[0]):
      for z in range(a.shape[1]):
        sum=sum+(a[k][z]*b[z][i])
        #print(sum)
        if z==a.shape[1]-1:
          cal.append(sum)
          result=np.array(cal)
          sum=0
  return result.reshape(a.shape[0],b.shape[1]).T

d= np.array([[-1, 2, 3], [4, -5, 6]])
e= np.array([[-9, 8, 7], [6, -5, 4]])

if d.shape[1]==e.shape[0]:
  e=e
else:
  print("計算が成り立ちません。転置等により計算ができるか確認してください") 
print(queue_multi(d,e.T))

計算が成り立ちません。転置等により計算ができるか確認してください
[[ 46  -4]
 [-34  73]]
