<a href="https://colab.research.google.com/github/YusukeAoki57/diveintocode-ml/blob/master/week4_%E6%8E%88%E6%A5%AD%E5%89%8D%E8%AA%B2%E9%A1%8C3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

問題1 これまで利用してきたクラスの列挙

Pandas : DataFrame
matplotlib : Axes
scikit-learn : LinearRegression 

問題2 これまで利用してきたメソッドやインスタンス変数の列挙

メソッド：fit、predict、mean, var, values
インスタンス変数：ロジスティック回帰のインスタンス変数、最近傍法の同変数、SVMの同変数、ランダムフォレストの同変数、線形回帰の同変数、決定木の同変数

問題3 標準化クラスをスクラッチで作成

In [23]:
class ScratchStandardScaler():
    """
    標準化のためのクラス
    Attributes
    ----------
    mean_ : 次の形のndarray, shape(n_features,)
        平均
    var_ : 次の形のndarray, shape(n_features,)
        分散
    """
    def fit(self, X):
        """
        標準化のために平均と標準偏差を計算する。
        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            訓練データ
        """
        self.mean_ =np.mean(X,axis=0)
        self.var_ =np.std(X,axis=0)
        
    def transform(self, X):
        """
        fitで求めた値を使い標準化を行う。
        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            特徴量
        Returns
        ----------
        X_scaled : 次の形のndarray, shape (n_samples, n_features)
            標準化された特緒量
        """
        X_scaled=(X-self.mean_)/self.var_
        return X_scaled

In [30]:
#挙動確認

import numpy as np
from sklearn.datasets import load_iris
data = load_iris()
X = data.data[:10]
scratch_scaler = ScratchStandardScaler()
scratch_scaler.fit(X)
print("平均 : {}".format(scratch_scaler.mean_))
print("分散 : {}".format(scratch_scaler.var_))
X_std = scratch_scaler.transform(X)
print(X_std)

平均 : [4.86 3.31 1.45 0.22]
分散 : [0.2764055  0.29137605 0.10246951 0.07483315]
[[ 0.86828953  0.65207831 -0.48795004 -0.26726124]
 [ 0.14471492 -1.06391725 -0.48795004 -0.26726124]
 [-0.57885968 -0.37751902 -1.46385011 -0.26726124]
 [-0.94064699 -0.72071813  0.48795004 -0.26726124]
 [ 0.50650222  0.99527742 -0.48795004 -0.26726124]
 [ 1.95365143  2.02487476  2.43975018  2.40535118]
 [-0.94064699  0.3088792  -0.48795004  1.06904497]
 [ 0.50650222  0.3088792   0.48795004 -0.26726124]
 [-1.66422159 -1.40711636 -0.48795004 -0.26726124]
 [ 0.14471492 -0.72071813  0.48795004 -1.60356745]]


問題4 【問題4】 四則演算を行うクラスの作成

In [16]:
import sys 
class CalcurateClass():
    """
    説明用の簡単なクラス
    Parameters
    ----------
    value : float or int
        初期値
    Attributes
    ----------
    value : float or int
        計算結果
    """
    def __init__(self, value):
        try:
          self.value = int(value)
          print("初期値{}が設定されました".format(self.value))
        except ValueError:
          print ("エラー：数字以外の文字を入力しないでください。")
          sys.exit()

    def add(self, value2):
        """
        受け取った引数をself.valueに加える
        """
        try:
          self.value += int(value2)
        except ValueError:
          print ("エラー：数字以外の文字を入力しないでください。")
          sys.exit()

    def hikizan(self, value3):
        """
        受け取った引数をself.valueに加える
        """
        try:
          self.value -= int(value3)
        except ValueError:
          print ("エラー：数字以外の文字を入力しないでください。")
          sys.exit()


    def kakezan(self, value4):
        """
        受け取った引数をself.valueに加える
        """
        try:
          self.value *= int(value4)
        except ValueError:
          print ("エラー：数字以外の文字を入力しないでください。")
          sys.exit()

    def warizan(self, value5):
        """
        受け取った引数をself.valueに加える
        """
        try:
          self.value /= int(value5)    
        except ValueError:
          print ("エラー：数字以外の文字を入力しないでください。")
          sys.exit()
example = CalcurateClass(5)
print("value : {}".format(example.value))
example.add('3')
print("value : {}".format(example.value))
example.hikizan('5')
print("value : {}".format(example.value))
example.warizan('2')
print("value : {}".format(example.value))
example.kakezan('2')
print("value : {}".format(example.value))

初期値5が設定されました
value : 5
value : 8
value : 3
value : 1.5
value : 3.0
